spring:
  jpa:
    hibernate:
      ddl-auto: update # TODO 추후 변경할 것
    properties:
      hibernate:
        format_sql: true
        highlight_sql: true
        use_sql_comments: true
    open-in-view: false
