spring:
  profiles:
    group:
      local-h2: local-env
      local-memory-h2: local-env
      local-dev-infra: local-dev-infra-env
      dev: dev-env
      prod: prod-env

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
