name: deployment-prod

on:
  push:
    branches:
      - main

jobs:
  deployment-prod:
    runs-on: ubuntu-latest
    steps:
      # 체크아웃
      - name: Checkout
        uses: actions/checkout@v4.1.1

      # 스프링 부트 yml 파일 작성
      - name: Make development environment configuration yml file
        run: mkdir -p ./src/main/resources \
          && touch ./src/main/resources/application-prod-env.yml \
          && echo "${{ secrets.PROD_ENV }}" > ./src/main/resources/application-prod-env.yml

      # appspec.yml 파일 작성
      - name: Make appspec yml for deployment
        env:
          APPSPEC: ${{ secrets.APPSPEC_PROD }}
        run: touch ./appspec.yml \
          && echo $APPSPEC | base64 --decode > ./appspec.yml # appspec.yml 파일 내용은 base64 인코딩해서 넣어줄 것

      # JDK 17 설치
      - name: Setup Java JDK 17 Adopt
        uses: actions/setup-java@v4.0.0
        with:
          java-version: '17'
          distribution: 'adopt'

      # jar 파일 생성
      - name: gradlew bootJar
        run: chmod +x ./gradlew && ./gradlew bootJar

      # AWS 인증
      - name: Configure AWS credentials for GitHub Actions
        uses: aws-actions/configure-aws-credentials@v4.0.2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      # 빌드 결과물을 S3 버킷에 업로드
      - name: Upload to AWS S3
        run: |
          aws deploy push \
            --application-name ${{ secrets.AWS_CODE_DEPLOY_PROD_APPLICATION_NAME }} \
            --ignore-hidden-files \
            --s3-location s3://${{ secrets.AWS_S3_BUCKET_NAME }}/$GITHUB_SHA.zip \
            --source .

      # S3 버킷에 있는 파일을 대상으로 CodeDeploy 실행
      - name: Deploy to AWS EC2 from S3
        run: |
          aws deploy create-deployment \
            --application-name ${{ secrets.AWS_CODE_DEPLOY_PROD_APPLICATION_NAME }} \
            --deployment-config-name CodeDeployDefault.AllAtOnce \
            --deployment-group-name ${{ secrets.AWS_CODE_DEPLOY_DEPLOYMENT_PROD_GROUP_NAME }} \
            --s3-location bucket=${{ secrets.AWS_S3_BUCKET_NAME }},key=$GITHUB_SHA.zip,bundleType=zip
